import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by Santiago Romero',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="icon-portfolio.svg"/>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
